"""add LLM insights fields

Revision ID: 0c46fbd8eae8
Revises: 9d640950786c
Create Date: 2026-09-22 15:35:04.657940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base_class  # noqa: F401  -- required: autogenerate references app.db.base_class.GUID() by dotted path but does not emit this import itself (a documented Alembic limitation for user-defined types).


# revision identifiers, used by Alembic.
revision: str = '0c46fbd8eae8'
down_revision: Union[str, None] = '9d640950786c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: if this migration adds a column with a NEW sa.Enum(...) type
    # (i.e. not already used by an existing table), Postgres needs that
    # enum TYPE created explicitly first -- CREATE TABLE auto-creates
    # enum types as a side effect, but ALTER TABLE ADD COLUMN does not.
    # Pattern: `my_enum = sa.Enum(..., name="..."); my_enum.create(op.get_bind(), checkfirst=True)`
    # before the add_column call, and `.drop(op.get_bind(), checkfirst=True)`
    # in downgrade() after dropping the column. (Hit this in Milestone 5 --
    # see docs/MILESTONES.md for the full story.)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_questions', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('improvement_suggestions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'improvement_suggestions')
    op.drop_column('resumes', 'ai_summary')
    op.drop_column('applications', 'interview_questions')
    # ### end Alembic commands ###
