"""create initial schema

Revision ID: 9d640950786c
Revises: 
Create Date: 2026-09-05 06:41:07.639358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base_class  # noqa: F401  -- required: autogenerate references app.db.base_class.GUID() by dotted path but does not emit this import itself (a documented Alembic limitation for user-defined types).
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d640950786c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: if this migration adds a column with a NEW sa.Enum(...) type
    # (i.e. not already used by an existing table), Postgres needs that
    # enum TYPE created explicitly first -- CREATE TABLE auto-creates
    # enum types as a side effect, but ALTER TABLE ADD COLUMN does not.
    # Pattern: `my_enum = sa.Enum(..., name="..."); my_enum.create(op.get_bind(), checkfirst=True)`
    # before the add_column call, and `.drop(op.get_bind(), checkfirst=True)`
    # in downgrade() after dropping the column. (Hit this in Milestone 5 --
    # see docs/MILESTONES.md for the full story.)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name='uq_skills_name')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RECRUITER', 'CANDIDATE', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('recruiter_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=False),
    sa.Column('min_education_level', sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', name='education_level'), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED', name='job_status'), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name=op.f('fk_jobs_recruiter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('resumes',
    sa.Column('candidate_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', name='file_type'), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('extracted_years_experience', sa.Float(), nullable=True),
    sa.Column('extracted_education_level', sa.Enum('HIGH_SCHOOL', 'ASSOCIATE', 'BACHELOR', 'MASTER', 'DOCTORATE', name='education_level'), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], name=op.f('fk_resumes_candidate_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_table('applications',
    sa.Column('job_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('resume_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'HIRED', name='application_status'), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('job_id', 'resume_id', name='uq_application_job_resume')
    )
    op.create_table('job_skills',
    sa.Column('job_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('skill_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skill')
    )
    op.create_table('resume_skills',
    sa.Column('resume_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('skill_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_skills_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_resume_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_skills')),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skill')
    )
    op.create_table('scores',
    sa.Column('application_id', app.db.base_class.GUID(), nullable=False),
    sa.Column('skills_match_score', sa.Float(), nullable=False),
    sa.Column('experience_match_score', sa.Float(), nullable=False),
    sa.Column('education_match_score', sa.Float(), nullable=False),
    sa.Column('certification_score', sa.Float(), nullable=False),
    sa.Column('project_score', sa.Float(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=False),
    sa.Column('resume_quality_score', sa.Float(), nullable=False),
    sa.Column('semantic_similarity_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.db.base_class.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_scores_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('application_id', name=op.f('uq_scores_application_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('resume_skills')
    op.drop_table('job_skills')
    op.drop_table('applications')
    op.drop_table('resumes')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
